# Form implementation generated from reading ui file 'padavan_l1_2.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Padavan_l1_2(object):
    def setupUi(self, Padavan_l1_2):
        Padavan_l1_2.setObjectName("Padavan_l1_2")
        Padavan_l1_2.resize(915, 657)
        Padavan_l1_2.setMaximumSize(QtCore.QSize(915, 657))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/recurce/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Padavan_l1_2.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Padavan_l1_2)
        self.centralwidget.setMinimumSize(QtCore.QSize(915, 657))
        self.centralwidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(15, 11, -1, 11)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(421, 483))
        self.label_2.setMaximumSize(QtCore.QSize(421, 483))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_4.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton_4.setStyleSheet("image:url(:/recurce/map.png);\n"
"border: none;")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton.setStyleSheet("image: url(:/recurce/book.png);\n"
"border: none;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_2.setStyleSheet("image: url(:/recurce/next_btn.png);\n"
"border: none;")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton_3.setStyleSheet("image: url(:/recurce/home.png);\n"
"border: none;")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.gridLayout.addWidget(self.frame_2, 2, 0, 1, 4)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.frame_3.setFont(font)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.gridLayout.addWidget(self.frame_3, 0, 0, 1, 4)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(445, 0))
        self.frame.setMaximumSize(QtCore.QSize(445, 16777215))
        self.frame.setStyleSheet("\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background:rgb(255, 255, 255);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color:rgb(85,116,226);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color:rgb(85,116,226);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color:rgb(85,116,226);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color:rgb(255, 255, 255);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color:rgb(255, 255, 255);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color:rgb(255, 255, 255);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color:rgb(255, 255, 255);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color:rgb(85,116,226);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setStyleSheet("\n"
"border: none;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -1105, 407, 1600))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 1600))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.question_1 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.question_1.setMaximumSize(QtCore.QSize(16777215, 180))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(18)
        self.question_1.setFont(font)
        self.question_1.setStyleSheet("\n"
"border: none;")
        self.question_1.setTitle("")
        self.question_1.setObjectName("question_1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.question_1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.q1_ask4 = QtWidgets.QRadioButton(self.question_1)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(18)
        self.q1_ask4.setFont(font)
        self.q1_ask4.setObjectName("q1_ask4")
        self.verticalLayout_5.addWidget(self.q1_ask4)
        self.q1_ask2 = QtWidgets.QRadioButton(self.question_1)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(18)
        self.q1_ask2.setFont(font)
        self.q1_ask2.setObjectName("q1_ask2")
        self.verticalLayout_5.addWidget(self.q1_ask2)
        self.q1_ask1 = QtWidgets.QRadioButton(self.question_1)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(18)
        self.q1_ask1.setFont(font)
        self.q1_ask1.setObjectName("q1_ask1")
        self.verticalLayout_5.addWidget(self.q1_ask1)
        self.q1_ask3 = QtWidgets.QRadioButton(self.question_1)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(18)
        self.q1_ask3.setFont(font)
        self.q1_ask3.setObjectName("q1_ask3")
        self.verticalLayout_5.addWidget(self.q1_ask3)
        self.verticalLayout_3.addWidget(self.question_1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 250))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(71,91,142);\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.question_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.question_2.setMaximumSize(QtCore.QSize(16777215, 180))
        self.question_2.setStyleSheet("\n"
"border: none;")
        self.question_2.setTitle("")
        self.question_2.setObjectName("question_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.question_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.q2_ask4 = QtWidgets.QRadioButton(self.question_2)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(18)
        self.q2_ask4.setFont(font)
        self.q2_ask4.setObjectName("q2_ask4")
        self.verticalLayout_6.addWidget(self.q2_ask4)
        self.q2_ask1 = QtWidgets.QRadioButton(self.question_2)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(18)
        self.q2_ask1.setFont(font)
        self.q2_ask1.setObjectName("q2_ask1")
        self.verticalLayout_6.addWidget(self.q2_ask1)
        self.q2_ask3 = QtWidgets.QRadioButton(self.question_2)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(18)
        self.q2_ask3.setFont(font)
        self.q2_ask3.setObjectName("q2_ask3")
        self.verticalLayout_6.addWidget(self.q2_ask3)
        self.q2_ask2 = QtWidgets.QRadioButton(self.question_2)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(18)
        self.q2_ask2.setFont(font)
        self.q2_ask2.setObjectName("q2_ask2")
        self.verticalLayout_6.addWidget(self.q2_ask2)
        self.verticalLayout_3.addWidget(self.question_2)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 250))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 90))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(71,91,142);\n"
"color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.question_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.question_3.setMaximumSize(QtCore.QSize(16777215, 180))
        self.question_3.setStyleSheet("\n"
"border: none;")
        self.question_3.setTitle("")
        self.question_3.setObjectName("question_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.question_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.q3_ask4 = QtWidgets.QRadioButton(self.question_3)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(18)
        self.q3_ask4.setFont(font)
        self.q3_ask4.setObjectName("q3_ask4")
        self.verticalLayout_7.addWidget(self.q3_ask4)
        self.q3_ask1 = QtWidgets.QRadioButton(self.question_3)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(18)
        self.q3_ask1.setFont(font)
        self.q3_ask1.setObjectName("q3_ask1")
        self.verticalLayout_7.addWidget(self.q3_ask1)
        self.q3_ask2 = QtWidgets.QRadioButton(self.question_3)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(18)
        self.q3_ask2.setFont(font)
        self.q3_ask2.setObjectName("q3_ask2")
        self.verticalLayout_7.addWidget(self.q3_ask2)
        self.q3_ask3 = QtWidgets.QRadioButton(self.question_3)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(18)
        self.q3_ask3.setFont(font)
        self.q3_ask3.setObjectName("q3_ask3")
        self.verticalLayout_7.addWidget(self.q3_ask3)
        self.verticalLayout_3.addWidget(self.question_3)
        self.proverka = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.proverka.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.proverka.setFont(font)
        self.proverka.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(71,91,142);\n"
"border-radius: 11px;")
        self.proverka.setObjectName("proverka")
        self.verticalLayout_3.addWidget(self.proverka)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.gridLayout.addWidget(self.frame, 1, 3, 1, 1)
        Padavan_l1_2.setCentralWidget(self.centralwidget)

        self.retranslateUi(Padavan_l1_2)
        QtCore.QMetaObject.connectSlotsByName(Padavan_l1_2)

        self.label_3.setStyleSheet("font-weight: bold")
        self.label.setStyleSheet("font-weight: bold")

    def retranslateUi(self, Padavan_l1_2):
        _translate = QtCore.QCoreApplication.translate
        Padavan_l1_2.setWindowTitle(_translate("Padavan_l1_2", "Level 1"))
        self.label_2.setText(_translate("Padavan_l1_2", "<html><head/><body><p><img src=\":/recurce/Padavan_l1_2_image.png\"/></p></body></html>"))
        self.label_3.setText(_translate("Padavan_l1_2", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">Подземелье</span></p></body></html>"))
        self.label.setText(_translate("Padavan_l1_2", "<html><head/><body><p align=\"center\">Тест 1. Вывод данных</p></body></html>"))
        self.label_4.setText(_translate("Padavan_l1_2", "<html><head/><body><p align=\"justify\">1. Какая команда отвечает</p><p align=\"justify\">за вывод   на экран?</p></body></html>"))
        self.q1_ask4.setText(_translate("Padavan_l1_2", "System.out.printf()"))
        self.q1_ask2.setText(_translate("Padavan_l1_2", "Write()"))
        self.q1_ask1.setText(_translate("Padavan_l1_2", "print()"))
        self.q1_ask3.setText(_translate("Padavan_l1_2", "Concole.WriteLine()"))
        self.label_5.setText(_translate("Padavan_l1_2", "<html><head/><body><p align=\"justify\">2. При помощи какой</p><p align=\"justify\">команды можно осуществить</p><p align=\"justify\">вывод ‘ab’ на экран после</p><p align=\"justify\">выполнения </p><p align=\"justify\">этой программы:</p></body></html>"))
        self.label_6.setText(_translate("Padavan_l1_2", "<html><head/><body><p align=\"center\">a = ‘a’</p><p align=\"center\">b = ‘b’</p></body></html>"))
        self.q2_ask4.setText(_translate("Padavan_l1_2", "print(a+b)"))
        self.q2_ask1.setText(_translate("Padavan_l1_2", "Write(a+b)"))
        self.q2_ask3.setText(_translate("Padavan_l1_2", "print(a,b)"))
        self.q2_ask2.setText(_translate("Padavan_l1_2", "Write(a, b)"))
        self.label_7.setText(_translate("Padavan_l1_2", "<html><head/><body><p align=\"justify\">3. При помощи какой </p><p align=\"justify\">команды можно осуществить</p><p align=\"justify\">вывод суммы переменных</p><p align=\"justify\">на экран после выполнения</p><p align=\"justify\">этой программы:</p></body></html>"))
        self.label_8.setText(_translate("Padavan_l1_2", "<html><head/><body><p align=\"center\">a = 1</p><p align=\"center\">b = 2</p></body></html>"))
        self.q3_ask4.setText(_translate("Padavan_l1_2", "print(a+b)"))
        self.q3_ask1.setText(_translate("Padavan_l1_2", "Write(a+b)"))
        self.q3_ask2.setText(_translate("Padavan_l1_2", "print(a,b)"))
        self.q3_ask3.setText(_translate("Padavan_l1_2", "Write(a, b)"))
        self.proverka.setText(_translate("Padavan_l1_2", "Проверить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Padavan_l1_2 = QtWidgets.QMainWindow()
    ui = Ui_Padavan_l1_2()
    ui.setupUi(Padavan_l1_2)
    Padavan_l1_2.show()
    sys.exit(app.exec())
